version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8

    steps:
      - checkout

      # Instalar dependencias adicionales
      - run:
          name: Install additional dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y \
            sqlite3 \
            curl \
            wget \
            git \
            unzip

      # Instalar dependencias de Python
      - run:
          name: Install Python dependencies
          command: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

      # Ejecutar pruebas y cobertura de c칩digo
      - run:
          name: Run tests and code coverage
          command: |
            python -m unittest tests.py

      # An치lisis est치tico de c칩digo
      - run:
          name: Static code analysis
          command: flake8 .

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
