version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y \
            sqlite3 \
            curl \
            wget \
            git \
            unzip
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run tests
          command: python -m unittest tests.py

  lint:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y \
            sqlite3 \
            curl \
            wget \
            git \
            unzip
            pip install flake8
      - run:
          name: Run linting
          command: flake8 .

  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y \
            sqlite3 \
            curl \
            wget \
            git \
            unzip
            python -m pip install --upgrade pip
            pip install -r requirements.txt

  integration_tests:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update && sudo apt-get install -y \
            sqlite3 \
            curl \
            wget \
            git \
            unzip
            python -m pip install --upgrade pip
            pip install -r requirements.txt
      - run:
          name: Run integration tests
          command: python -m unittest integration_tests.py  # Ejecutar las pruebas de integración

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
      - lint
      - build
      - integration_tests:
          requires:
            - build
